# Generated by Django 5.1.7 on 2025-04-05 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=128)),
                ('confirmPassword', models.CharField(max_length=128)),
                ('dob', models.DateField()),
                ('country', models.CharField(choices=[('IN', 'INDIA'), ('CN', 'CHINA'), ('KR', 'KOREA'), ('SRI', 'SHRILANKA')], max_length=3)),
                ('address', models.TextField()),
                ('terms', models.BooleanField(default=False)),
            ],
        ),
    ]
