# Generated by Django 5.1.7 on 2025-04-05 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_registrationdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationdata',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
